---
- import_tasks: preflight.yml
  tags:
    - coredns_install
    - coredns_configure
    - coredns_run

- import_tasks: install.yml
  become: true
  tags:
    - coredns_install

- import_tasks: configure.yml
  become: true
  tags:
    - coredns_configure

- name: Ensure CoreDNS is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: coredns
    enabled: true
  tags:
    - coredns_run
